Repository deinsoftware/fun-with-flags, pull requests merged in 2023-08, with the labels that each got.

#41 Event dates order
  .env.template
  .vscode/settings.json
  src/helpers/dates.ts
  src/helpers/events.test.ts
  src/helpers/events.ts
Labels: enhancement

#47 Project config
  .vscode/settings.json
  package-lock.json
  package.json
Labels: enhancement

#48 Refactor helpers
  .github/workflows/build.yml
  src/helpers/dates.test.ts
  src/helpers/dates.ts
Labels: enhancement

#49 Select country
  package-lock.json
  package.json
  src/app/components/atoms/country-list/SelectTimeZone.tsx
  src/app/components/atoms/country-list/TimeZones.tsx
  src/app/components/atoms/util/toggle/Toggle.module.css
  src/app/components/atoms/util/toggle/Toggle.tsx
  src/app/components/molecules/country-combo/useGetInfoDates.ts
  src/app/components/molecules/country-list/CountryList.tsx
  src/app/components/molecules/select-country/SelectCountry.module.css
  src/app/components/molecules/select-country/SelectCountry.tsx
  src/app/components/organisms/events/CreateEvent.module.css
  src/app/components/organisms/events/CreateEvent.tsx
  src/app/components/organisms/events/CreateEvent.types.ts
  src/app/components/organisms/events/useGetFormData.ts
  src/app/components/organisms/ui/Footer.tsx
  src/app/context/timeZoneContext.tsx
  src/helpers/dates.ts
  src/helpers/events.ts
  src/helpers/flags.ts
  src/libs/iconConfig.ts
  src/types/context.types.ts
Labels: enhancement

#54 add helpers for am/pm on dates
  package-lock.json
  package.json
  src/app/components/atoms/country-combo/DatesToRender.tsx
  src/app/components/atoms/country-list/TimeZones.module.css
  src/app/components/atoms/country-list/TimeZones.tsx
  src/app/components/molecules/select-country/SelectCountry.tsx
  src/app/components/organisms/events/CreateEvent.tsx
  src/app/components/organisms/events/CreateEvent.types.ts
  src/app/components/organisms/events/useGetFormData.ts
  src/app/hooks/useDebounce.ts
  src/helpers/dates.test.ts
  src/helpers/dates.ts
  src/helpers/events.test.ts
  src/helpers/events.ts
  src/helpers/flags.ts
  src/helpers/get-time-zone.ts
  src/types/context.types.ts
  src/types/countries.types.ts
  src/types/dates.types.ts
  src/types/timezones.types.ts
Labels: enhancement

#56 fix combo message when using acronyms
  src/app/components/atoms/country-combo/DatesToRender.tsx
  src/app/components/organisms/events/CreateEvent.tsx
Labels: bug

#57 CreateEvent visual bugs 🐱‍🏍
  src/app/components/atoms/util/toggle/Toggle.module.css
  src/app/components/molecules/country-list/CountryList.module.css
  src/app/components/organisms/events/CreateEvent.module.css
  src/app/components/organisms/events/CreateEvent.tsx
Labels: bug

#65 Dev
  src/app/api/timezones/route.ts
  src/app/components/atoms/country-combo/DatesToRender.module.css
  src/app/components/atoms/country-combo/DatesToRender.tsx
  src/app/components/atoms/ui/button/Button.module.css
  src/app/components/atoms/ui/button/Button.tsx
  src/app/components/atoms/util/hashtags-input/HashtagsInput.module.css
  src/app/components/atoms/util/hashtags-input/HashtagsInput.tsx
  src/app/components/atoms/util/time-picker/TimePicker.tsx
  src/app/components/atoms/util/toggle/Toggle.module.css
  src/app/components/molecules/country-combo/ComboboxCountries.tsx
  src/app/components/molecules/country-list/CountryList.module.css
  src/app/components/molecules/select-country/SelectCountry.module.css
  src/app/components/molecules/select-country/SelectCountry.tsx
  src/app/components/organisms/events/CreateEvent.module.css
  src/app/components/organisms/events/CreateEvent.tsx
  src/app/components/organisms/events/CreateEvent.types.ts
  src/app/components/organisms/events/useGetFormData.ts
  src/app/context/timeZoneContext.tsx
  src/helpers/dates.test.ts
  src/helpers/dates.ts
  src/helpers/events.ts
  src/helpers/get-time-zone.ts
  src/helpers/locale.test.ts
  src/helpers/locale.ts
  src/helpers/share-events.test.ts
  src/helpers/share-events.ts
  src/helpers/timezones.test.ts
  src/helpers/timezones.ts
Labels: enhancement

#68 fix auto clean on add
  src/app/components/atoms/util/hashtags-input/HashtagsInput.tsx
Labels: bug

#69 code smells
  src/app/components/atoms/country-list/SelectTimeZone.tsx
  src/app/components/molecules/gdpr/CookiePolicy.jsx
  src/app/components/organisms/events/CreateEvent.tsx
  src/helpers/dates.ts
  src/helpers/flags.ts
  src/types/countries.types.ts
Labels: code-smell

#70 Localstorage signature
  .env.template
  src/app/components/atoms/auth/LoginButton.tsx
  src/app/components/atoms/ui/button/Button.tsx
  src/app/components/atoms/util/toggle/Toggle.tsx
  src/app/components/organisms/events/CreateEvent.tsx
  src/app/components/organisms/events/CreateEvent.types.ts
  src/app/components/organisms/events/local-storage.ts
  src/app/components/organisms/events/useFormData.ts
  src/app/components/organisms/events/useGetFormData.ts
  src/app/context/timeZoneContext.tsx
  src/app/context/useGetTimes.ts
  src/helpers/dates.test.ts
  src/helpers/dates.ts
Labels: enhancement

#73 add localstorage signature and some fixes
  .env.template
  src/app/components/atoms/auth/LoginButton.tsx
  src/app/components/atoms/country-combo/DatesToRender.module.css
  src/app/components/atoms/country-list/SelectTimeZone.tsx
  src/app/components/atoms/ui/button/Button.tsx
  src/app/components/atoms/util/hashtags-input/HashtagsInput.tsx
  src/app/components/atoms/util/toggle/Toggle.tsx
  src/app/components/molecules/country-combo/ComboboxCountries.module.css
  src/app/components/molecules/country-combo/ComboboxCountries.tsx
  src/app/components/molecules/gdpr/CookiePolicy.jsx
  src/app/components/molecules/select-country/SelectCountry.module.css
  src/app/components/molecules/select-country/SelectCountry.tsx
  src/app/components/organisms/events/CreateEvent.module.css
  src/app/components/organisms/events/CreateEvent.tsx
  src/app/components/organisms/events/CreateEvent.types.ts
  src/app/components/organisms/events/local-storage.ts
  src/app/components/organisms/events/useFormData.ts
  src/app/components/organisms/events/useGetFormData.ts
  src/app/context/timeZoneContext.tsx
  src/app/context/useGetTimes.ts
  src/helpers/dates.test.ts
  src/helpers/dates.ts
  src/helpers/flags.ts
  src/types/countries.types.ts
Labels: bug

#75 Mrredu/fix/74 gmt is not displayed when offset is 0
  src/app/components/atoms/country-combo/DatesToRender.tsx
  src/app/components/molecules/select-country/SelectCountry.tsx
  src/app/components/organisms/events/useFormData.ts
  src/helpers/dates.test.ts
  src/helpers/dates.ts
Labels: bug

#77 ci(tools): remove matrix verification in all OS
  .github/workflows/build.yml
  .github/workflows/sonarcloud.yml
Labels: enhancement

#78 fix sonar configuration
  .github/workflows/build.yml
  .github/workflows/sonarcloud.yml
Labels: bug

#80 update project versions
  .eslintrc.json
  .vitest/setup.ts
  package-lock.json
  package.json
Labels: enhancement

#82 Equiman/fix/toggle combo config
  src/app/components/atoms/country-combo/DatesToRender.tsx
  src/app/components/molecules/country-combo/ComboboxCountries.tsx
  src/app/components/molecules/select-country/SelectCountry.tsx
  src/app/components/organisms/events/CreateEvent.module.css
  src/app/components/organisms/events/CreateEvent.tsx
  src/helpers/dates.ts
Labels: bug

#83 fix gmt, move format from context
  src/app/components/atoms/country-combo/DatesToRender.tsx
  src/app/components/molecules/country-combo/ComboboxCountries.tsx
  src/app/components/molecules/country-list/CountryList.module.css
  src/app/components/molecules/select-country/SelectCountry.tsx
  src/app/components/organisms/events/CreateEvent.tsx
  src/app/components/organisms/events/useFormData.ts
  src/app/context/timeZoneContext.tsx
  src/app/context/useGetTimes.ts
  src/helpers/dates.ts
Labels: bug

#84 toggle format fixed, move format from context
  .eslintrc.json
  .vitest/setup.ts
  package-lock.json
  package.json
  src/app/components/atoms/country-combo/DatesToRender.tsx
  src/app/components/molecules/country-combo/ComboboxCountries.tsx
  src/app/components/molecules/country-list/CountryList.module.css
  src/app/components/molecules/select-country/SelectCountry.tsx
  src/app/components/organisms/events/CreateEvent.module.css
  src/app/components/organisms/events/CreateEvent.tsx
  src/app/components/organisms/events/useFormData.ts
  src/app/context/timeZoneContext.tsx
  src/app/context/useGetTimes.ts
  src/helpers/dates.ts
Labels: bug
